export const ADD_BUDGET_CATEGORY = 'ADD_BUDGET_CATEGORY';
export const DEL_BUDGET_CATEGORY = 'DEL_BUDGET_CATEGORY';
export const INIT_BUDGET_CATEGORY = 'INIT_BUDGET_CATEGORY';
export const ADD_BUDGET_ITEM = 'ADD_BUDGET_ITEM';
export const DEL_BUDGET_ITEM = 'DEL_BUDGET_ITEM';
export const ADD_NEW_TRANSACTION = 'ADD_NEW_TRANSACTION';